In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv"
data = pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [2]:
data["EducationLevel"] = data["EducationLevel"].map({"高中以下": 0, "大學": 1, "碩士以上": 2})
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [3]:
# 僅需城市A 與城市B 兩個Label, 再透過之間的關係就能區隔城市A, B, C 三者的關係
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder() # 創建一名稱為onehot_encoder 編碼器
onehot_encoder.fit(data[["City"]]) # 讓編碼器看過特徵(.fit), 只接受傳入是一組二維的矩陣(雙中括號)-> :[["x"]]
city_encoded = onehot_encoder.transform(data[["City"]]).toarray() # 做轉換,再用(.toarray) 將稀疏矩陣-> 我們要的矩陣結果
city_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [4]:
# 將轉換結果加入原始數據
data[["City A", "City B", "City C"]] = city_encoded
data

YearsExperience  EducationLevel City  Salary  City A  City B  City C
0               3.0               1  城市A    45.9     1.0     0.0     0.0
1               7.8               2  城市C    80.5     0.0     0.0     1.0
2               2.3               0  城市A    25.2     1.0     0.0     0.0
3               5.1               0  城市A    30.4     1.0     0.0     0.0
4              10.0               2  城市B    65.7     0.0     1.0     0.0
5               1.2               2  城市C    60.8     0.0     0.0     1.0
6               8.6               1  城市C    50.1     0.0     0.0     1.0
7               6.9               2  城市A    70.3     1.0     0.0     0.0
8               4.2               1  城市A    40.7     1.0     0.0     0.0
9               2.4               0  城市A    28.1     1.0     0.0     0.0
10              5.3               0  城市A    32.0     1.0     0.0     0.0
11              3.9               1  城市A    48.3     1.0     0.0     0.0
12              7.2               2  城市C    84.2     0.0     0.0     1.0
13             10.0               2  城市B    70.9     0.0     1.0     0.0
14              1.5               2  城市C    62.4     0.0     0.0     1.0
15              8.4               1  城市C    55.6     0.0     0.0     1.0
16              6.5               2  城市A    72.7     1.0     0.0     0.0
17              4.8               1  城市A    42.9     1.0     0.0     0.0
18              2.1               0  城市A    26.5     1.0     0.0     0.0
19              5.2               0  城市A    31.6     1.0     0.0     0.0
20              3.5               1  城市A    43.8     1.0     0.0     0.0
21              7.6               2  城市C    78.3     0.0     0.0     1.0
22             10.0               2  城市B    63.6     0.0     1.0     0.0
23              1.8               2  城市C    58.0     0.0     0.0     1.0
24              8.2               1  城市C    48.3     0.0     0.0     1.0
25              6.3               2  城市A    68.4     1.0     0.0     0.0
26              4.6               1  城市A    38.5     1.0     0.0     0.0
27              2.5               0  城市A    24.9     1.0     0.0     0.0
28              5.0               0  城市A    29.7     1.0     0.0     0.0
29              3.6               1  城市A    41.6     1.0     0.0     0.0
30              7.4               2  城市C    76.9     0.0     0.0     1.0
31             10.0               2  城市B    60.2     0.0     1.0     0.0
32              1.7               2  城市C    56.3     0.0     0.0     1.0
33              8.0               1  城市C    45.2     0.0     0.0     1.0
34              6.1               2  城市A    65.9     1.0     0.0     0.0
35              4.3               1  城市A    36.7     1.0     0.0     0.0

In [5]:
# 將不需要的行移除(注意, 因為資料在這裡顯示的方式為橫行直列, 當要刪除「列」時 axis = 1； 要刪除「行」時 axis = 0)
data = data.drop(["City", "City C"], axis = 1)
data

YearsExperience  EducationLevel  Salary  City A  City B
0               3.0               1    45.9     1.0     0.0
1               7.8               2    80.5     0.0     0.0
2               2.3               0    25.2     1.0     0.0
3               5.1               0    30.4     1.0     0.0
4              10.0               2    65.7     0.0     1.0
5               1.2               2    60.8     0.0     0.0
6               8.6               1    50.1     0.0     0.0
7               6.9               2    70.3     1.0     0.0
8               4.2               1    40.7     1.0     0.0
9               2.4               0    28.1     1.0     0.0
10              5.3               0    32.0     1.0     0.0
11              3.9               1    48.3     1.0     0.0
12              7.2               2    84.2     0.0     0.0
13             10.0               2    70.9     0.0     1.0
14              1.5               2    62.4     0.0     0.0
15              8.4               1    55.6     0.0     0.0
16              6.5               2    72.7     1.0     0.0
17              4.8               1    42.9     1.0     0.0
18              2.1               0    26.5     1.0     0.0
19              5.2               0    31.6     1.0     0.0
20              3.5               1    43.8     1.0     0.0
21              7.6               2    78.3     0.0     0.0
22             10.0               2    63.6     0.0     1.0
23              1.8               2    58.0     0.0     0.0
24              8.2               1    48.3     0.0     0.0
25              6.3               2    68.4     1.0     0.0
26              4.6               1    38.5     1.0     0.0
27              2.5               0    24.9     1.0     0.0
28              5.0               0    29.7     1.0     0.0
29              3.6               1    41.6     1.0     0.0
30              7.4               2    76.9     0.0     0.0
31             10.0               2    60.2     0.0     1.0
32              1.7               2    56.3     0.0     0.0
33              8.0               1    45.2     0.0     0.0
34              6.1               2    65.9     1.0     0.0
35              4.3               1    36.7     1.0     0.0

In [6]:
# 分成訓練集與測試集
from sklearn.model_selection import train_test_split
x = data[["YearsExperience",	"EducationLevel",	"City A", "City B"]]
y = data["Salary"]
# 兩成測試集, 固定分割的方式random_state = ?(數字)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 87)
# 原先為Pandas 的形式方便閱讀, 將其用Numpy轉換為矩陣形式方便計算
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [7]:
# 用Feature Scaling 做加速, 減少迭代更新到近最低點所需的次數, 功能像是幫各個x 做Normalize
from sklearn.preprocessing import StandardScaler
# 這裡是做標準化Standardization
scaler = StandardScaler() # 創建一名稱為scalar 的類別
scaler.fit(x_train) # 再讓它看過訓練集的特徵資料(.fit)
x_train = scaler.transform(x_train)
# 注意我們不能算測試集的平均值, 變異數, 標準差來做Normalize, 直接使用前面訓練集的
x_test = scaler.transform(x_test)

In [8]:
# 設定w1, w2, b...
import numpy as np
w = np.array([1, 2, 3, 4])
b = 1
y_pred = (x_train*w).sum(axis=1) + b
y_pred

array([ 1.19646915,  1.08090953,  4.41120425,  0.81127042,  4.488244  ,
        1.27350889, -1.18044209, 11.32906649, -3.26051522, -2.40346469,
        0.92683004, -1.02636259, 11.32906649, -3.43218037, -1.2478685 ,
       11.32906649,  1.04238966, -1.17082875, -3.37607484, -1.10340234,
       -1.28638837, -2.28790507,  0.58015118, -1.20934863, -3.50922011,
       -3.27810088, -3.35514062, 11.32906649])

In [9]:
# Cost Function = (真實數據 - 預測值)^2, 再做mean
((y_train - y_pred)**2).mean()

2729.861648680892

In [10]:
#定義Cost Function
def compute_cost(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  cost = ((y - y_pred)**2).mean()
  return cost

In [11]:
w = np.array([0, 2, 2, 4])
b = 0
compute_cost(x_train, y_train, w, b)

2822.234209806599

In [12]:
# 設定optimizer - Gradient Descent
y_pred = (x_train*w).sum(axis=1) + b
b_gradient = (y_pred - y_train).mean()
# x_train.shape 告訴我們x_train 大小, 我們要x_train.shape 當中第二個值的大小的0矩陣, 故[1]
w_gradient = np.zeros(x_train.shape[1])

for i in range(x_train.shape[1]):
  w_gradient[i] = (x_train[:, i]*(y_pred - y_train)).mean()

w_gradient, b_gradient

# 取出x_train 第一列: x_train[:,0]
# w1_gradiet = (x_train[:, 0]*(y_pred - y_train)).mean()
# w2_gradiet = (x_train[:, 1]*(y_pred - y_train)).mean()
# w3_gradiet = (x_train[:, 2]*(y_pred - y_train)).mean()
# w4_gradiet = (x_train[:, 3]*(y_pred - y_train)).mean()
# w1_gradiet, w2_gradiet, w3_gradiet, w4_gradiet

(array([ -6.35305402, -12.62906041,  10.23132015,  -1.76948291]),
 -50.949999999999996)

In [13]:
def compute_gradient(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  w_gradient = np.zeros(x.shape[1])
  b_gradient = (y_pred - y).mean()
  for i in range(x.shape[1]):
    w_gradient[i] = (x[:, i]*(y_pred - y)).mean()
  return w_gradient, b_gradient

In [14]:
w = np.array([1, 2, 2, 4])
b = 1
compute_gradient(x_train, y_train, w, b)

(array([ -5.35305402, -12.20449464,   9.61677346,  -1.12136056]), -49.95)

In [15]:
# Learning Rate
w = np.array([1, 2, 2, 4])
b = 1
learning_rate = 0.001
print(compute_cost(x_train, y_train, w, b))
w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)
w = w - w_gradient*learning_rate
b = b - b_gradient*learning_rate
w, b
print(compute_cost(x_train, y_train, w, b))

2709.6281017583538
2704.098469896066


In [16]:
# 設定顯示格式
np.set_printoptions(formatter={'float': '{: .2e}'.format})

# 貼前面寫過的Gradient Descent 來用
# 定義Gradient Descent 的function
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, iter_times, print_iter=1000):
  # hist 是用來儲存cost, w, b 的列表
  c_hist = []
  w_hist = []
  b_hist = []

  w = w_init
  b = b_init

  # 建立一for 迴圈進行iter_times 次迭代
  for i in range(iter_times):
    # w_gradient, b_gradient = compute_gradient(x, y, w, b)
    w_gradient, b_gradient = gradient_function(x, y, w, b)
    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    # cost = compute_cost(x, y, w, b)
    cost = cost_function(x, y, w, b)

    w_hist.append(w)
    b_hist.append(b)
    c_hist.append(cost)

    if i%print_iter==0:
      # .4f:小數點後4 位，.4e: 小數點後4 位+科學符號，加空格處理負號問題
      print(f"Iteration {i:5} : Cost:{cost:.2e}, w:{w}, b:{b: .2e}, w_gradient:{w_gradient}, b_gradient:{b_gradient: .2e}")

  return w, b, w_hist, b_hist, c_hist

In [17]:
# 貼前面寫過的Gradient Descent 來用
w_init = np.array([1, 2, 2, 4])
b_init = 0
learning_rate = 1.0e-2
iter_times=10000
#把函式當參數傳入: cost_function -> compute_cost, gradient_function -> compute_gradient, print_iter 已經設定好1000 故無須再設定
w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, iter_times)

# 注意: 上方.2e 是numpy 的矩陣格式，遇到錯誤可能會需要移除

Iteration     0 : Cost:2.75e+03, w:[ 1.05e+00  2.12e+00  1.90e+00  4.01e+00], b: 5.10e-01, w_gradient:[-5.35e+00 -1.22e+01  9.62e+00 -1.12e+00], b_gradient:-5.10e+01
Iteration  1000 : Cost:2.53e+01, w:[ 3.73e+00  1.39e+01 -1.82e+00 -3.51e+00], b: 5.09e+01, w_gradient:[-9.61e-02 -6.24e-02 -8.60e-02  7.25e-02], b_gradient:-2.20e-03
Iteration  2000 : Cost:2.52e+01, w:[ 4.09e+00  1.41e+01 -1.49e+00 -3.76e+00], b: 5.09e+01, w_gradient:[-8.25e-03 -5.10e-03 -7.72e-03  5.60e-03], b_gradient:-9.50e-08
Iteration  3000 : Cost:2.52e+01, w:[ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b: 5.09e+01, w_gradient:[-6.98e-04 -4.34e-04 -6.57e-04  4.72e-04], b_gradient:-4.10e-12
Iteration  4000 : Cost:2.52e+01, w:[ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b: 5.09e+01, w_gradient:[-5.92e-05 -3.68e-05 -5.57e-05  4.00e-05], b_gradient:-3.48e-13
Iteration  5000 : Cost:2.52e+01, w:[ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b: 5.09e+01, w_gradient:[-5.02e-06 -3.12e-06 -4.73e-06  3.40e-06], b_gradient:-3.46e-13
Iter

In [18]:
w_final, b_final

(array([ 4.12e+00,  1.41e+01, -1.46e+00, -3.78e+00]), 50.949999999999655)

In [19]:
y_pred = (w_final*x_test).sum(axis=1)+b_final
# 轉換為Pandas 的形式方便閱讀
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

y_pred  y_test
20  44.035070    43.8
16  67.440313    72.7
5   61.954972    60.8
27  23.802655    24.9
32  62.748179    56.3
2   23.485373    25.2
1   72.425307    80.5
7   68.074879    70.3

In [20]:
compute_cost(x_test, y_test, w_final, b_final)

18.116060544218655

In [21]:
# 5.3 碩士以上 城市A
# 7.2 高中以下 城市B
x_real = np.array([[5.3, 2, 1, 0], [7.2, 0, 0, 1]])
x_real = scaler.transform(x_real)
y_real = (w_final*x_real).sum(axis=1) + b_final
y_real

array([ 6.55e+01,  2.34e+01])