In [1]:
import torch

In [2]:
# 0維
x = torch.tensor(87)
x.shape

torch.Size([])

In [3]:
# 1維
x = torch.tensor([1, 2, 3])
x.shape

torch.Size([3])

In [4]:
# 3維, 看[]的數量
x = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
x.shape

torch.Size([1, 2, 3])

In [5]:
# 固定隨機的數值
torch.manual_seed(87)
x = torch.rand(2, 3, 4)
x

tensor([[[0.0036, 0.8931, 0.4548, 0.9815],
         [0.5443, 0.1487, 0.0450, 0.5285],
         [0.6307, 0.6676, 0.3723, 0.8175]],

        [[0.1480, 0.5822, 0.1032, 0.3165],
         [0.9750, 0.1861, 0.9619, 0.9053],
         [0.7163, 0.3249, 0.4789, 0.0177]]])

In [6]:
x = torch.zeros(2, 3, 4)
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
x = torch.ones(2, 3, 4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# 排列
x = torch.arange(0, 11, 2)
x

tensor([ 0,  2,  4,  6,  8, 10])

In [9]:
x = torch.tensor([1, 2, 3],
                 dtype = torch.float64, # 資料型態
                 device = None, # 用CPU, 或Cuda 調用GPU 做計算
                 requires_grad = True) # 是否追蹤梯度, 方便日後計算
x.dtype, x.device, x.requires_grad

(torch.float64, device(type='cpu'), True)

In [10]:
# 讀值
x = torch.tensor([[0.1, 0.2, 0.3],
                  [0.4, 0.5, 0.6]])
x[0][0]

tensor(0.1000)

In [11]:
# 矩陣乘法
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
y = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.matmul(x, y)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [12]:
# 轉置
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
x.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [13]:
# 改變矩陣形狀
x = torch.arange(0,10)
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# 應用Pytorch 套件將numpy 的array 格式轉換為torch 的tensor 格式
import numpy as np
array = np.array([1, 2, 3])
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3]), tensor([1, 2, 3]))

In [15]:
# 應用Pytorch 套件將torch 的tensor 格式轉換為numpy 的array 格式
tensor = torch.tensor([1, 2, 3])
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3]), array([1, 2, 3]))